[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder

; LittleFS filesystem
board_build.filesystem = littlefs
board_build.partitions = partitions.csv

; Force erase before every upload so partition table is always reflashed cleanly
upload_flags =
    --before=default_reset
    --after=hard_reset

build_flags =
    -DCORE_DEBUG_LEVEL=3

lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ST7735 and ST7789 Library

; Extra scripts to flash partition table explicitly
extra_scripts = pre:flash_extras.py
